"use client"

// Re-export Phosphor Icons through a client boundary for use in server components
export {
  Trophy,
  Crown,
  Medal,
  MedalMilitary,
  UsersThree,
  CalendarBlank,
  Plus,
  Prohibit,
  ShieldCheck,
  Warning,
  User,
  Clock,
  ArrowLeft,
  Crosshair,
  List,
  X,
  SignOut,
  SignIn,
  ChartBar,
  GameController,
  ClockCounterClockwise,
  GearSix,
  ArrowCounterClockwise,
  ArrowsClockwise,
  PencilSimple,
  FloppyDisk,
  Sparkle,
  CircleNotch,
  CheckCircle,
  XCircle,
  WarningCircle,
  Lightning,
  Translate,
  UserPlus,
  House,
  ArrowSquareOut,
  TrendUp,
  Check,
  CaretRight,
  Circle,
} from "@phosphor-icons/react"
